

import type { Metadata } from "next";
import "./globals.css";
import { Experimental_CssVarsProvider as CssVarsProvider, ThemeProvider, useColorScheme } from "@mui/material/styles";
import NavBar from "./common/nav";
import ReduxWrapper from "@/providers/ReduxWrapper";
import ThemeWrapper from "./ThemeWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <ReduxWrapper>
          <CssVarsProvider defaultMode="light" disableTransitionOnChange>
          <ThemeWrapper>
            <NavBar/>
            {children}
          </ThemeWrapper>
          </CssVarsProvider>
        </ReduxWrapper>
      </body>
    </html>
  );
}
